
-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기

SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS 
FROM CAR_RENTAL_COMPANY_CAR 
WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE ORDER BY CAR_TYPE

-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기 (서브쿼리 까다롭)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (MONTH(START_DATE) BETWEEN 8 AND 10)
    AND CAR_ID IN ( SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
                    GROUP BY CAR_ID
                    HAVING COUNT(HISTORY_ID)>=5)
GROUP BY MONTH, CAR_ID
HAVING RECORDS >0
ORDER BY MONTH, CAR_ID DESC

-- 성분으로 구분한 아이스크림 총 주문량
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN ICECREAM_INFO I ON F.FLAVOR=I.FLAVOR
GROUP BY INGREDIENT_TYPE ORDER BY TOTAL_ORDER


