-- 프로그래머스 JOIN 파트
-- 주문량이 많은 아이스크림들 조회하기

SELECT J.FLAVOR
FROM JULY J LEFT JOIN FIRST_HALF F ON J.FLAVOR=F.FLAVOR
GROUP BY FLAVOR
ORDER BY (SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER)) DESC
LIMIT 3

-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기

SELECT A.CAR_ID, A.CAR_TYPE, ROUND(DAILY_FEE *30* (100- DISCOUNT_RATE)*0.01 ) AS FEE -- RIGHT(DISCOUNT_RATE,0)
FROM CAR_RENTAL_COMPANY_CAR A 
    JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE='30일 이상') C
    ON A.CAR_TYPE=C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND A.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE>='2022-11-01' AND START_DATE<'2022-12-01')
GROUP BY A.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER by FEE DESC, A.CAR_TYPE, A.CAR_ID DESC

-- 5월 식품들의 총매출 조회하기

SELECT B.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE '2022-05%'
GROUP BY B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID

-- 조건에 맞는 도서와 저자 리스트 출력하기

SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE

-- 그룹별 조건에 맞는 식당 목록 출력하기