-- 프로그래머스 SELECT 파트
-- 인기있는 아이스크림

SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID

-- 흉부외과 또는 일반외과 의사 목록 출력하기

SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD='CS' OR MCDP_CD='GS'
-- WHERE MCDP_CD IN ('CS','GS')
ORDER BY HIRE_YMD DESC, DR_NAME

-- 조건에 부합하는 중고거래 댓글 조회하기

SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS b
INNER JOIN USED_GOODS_REPLY AS r
ON b.BOARD_ID = r.BOARD_ID
-- WHERE MONTH(r.CREATED_DATE) = 10
-- WHERE DATE_FORMAT(r.CREATED_DATE, '%Y-%m') = '2022-10'
-- WHERE SUBSTR(r.CREATED_DATE,1,7) = '2022-10' 
-- WHERE r.CREATED_DATE BETWEEN ('2022-10-01') AND ('2022-10-31') 
WHERE b.CREATED_DATE like '2022-10%'
ORDER BY r.CREATED_DATE, b.TITLE

-- 과일로 만든 아이스크림 고르기 (INNER JOIN: 행들간 교집합)

SELECT A.FLAVOR
FROM FIRST_HALF AS A
INNER JOIN ICECREAM_INFO AS B ON A.FLAVOR=B.FLAVOR
WHERE A.TOTAL_ORDER>=3000 AND B.INGREDIENT_TYPE='fruit_based'
ORDER BY A.TOTAL_ORDER DESC

-- 서울에 위치한 식당 목록 출력하기 (집계함수-> 항상 GROUP BY와 함께)

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A
JOIN REST_REVIEW AS B ON A.REST_ID=B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY A.REST_ID
ORDER BY SCORE DESC, A.FAVORITES DESC
