-- 프로그래머스 SELECT 파트
-- 업그레이드 된 아이템 구하기

SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN 
    (SELECT A.ITEM_ID FROM ITEM_INFO I, ITEM_TREE A WHERE I.ITEM_ID=A.PARENT_ITEM_ID AND I.RARITY='RARE')
ORDER BY ITEM_ID DESC

-- Python 개발자 찾기 (OR을 IN으로 사용해서 간단하게)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPER_INFOS 
WHERE 'Python' IN (SKILL_1,SKILL_2,SKILL_3) ORDER BY ID

-- 조건에 맞는 개발자 찾기  (비트 연산자 사용)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS AS D
WHERE D.SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'Python') 
OR D.SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID

-- 잔챙이 잡은 수 구하기 (NULL 비교는 IS NULL)

SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO WHERE LENGTH IS NULL

-- 가장 큰 물고기 10마리 구하기 (LIMIT)
SELECT ID, LENGTH FROM FISH_INFO ORDER BY LENGTH DESC, ID LIMIT 10